### ISSUE TITLE
Could not find the OPS under nos

### ISSUE THREAD

**Issue by Yasin-Munshi** [CiscoTestAutomation/CL-DEVWKS-2808#2]
Hello, 
I have a full installation of pyats. I am getting the following error on Nexus OS 
>>> bgp = WAN1.learn('bgp')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "src/genie/conf/base/device.py", line 623, in genie.conf.base.device.Device.learn
  File "src/genie/ops/utils.py", line 51, in genie.ops.utils.get_ops
LookupError: Could not find the OPS under nos

**Comment by jeaubin** [comment]
The os should be nxos instead of nos
